export const AUTH_START = "AUTH_START";
export const FETCH_USER = "FETCH_USER";
export const FETCH_USER_FAILED = "FETCH_USER_FAILED";
export const FETCH_USER_SUCCEED = "FETCH_USER_SUCCEED";

export const SUBMISSION_STARTED = "SUBMISSION_STARTED";
export const SUBMISSION_FAILED = "SUBMISSION_FAILED";
export const SUBMISSION_SUCCESSFUL = "SUBMISSION_SUCCESSFUL";
